// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_OPWwMgpU2WUuK_08Bw7Un1D_xgYSgUk',
    appId: '1:884044940776:web:d3c23de3c3c8e7b69a105d',
    messagingSenderId: '884044940776',
    projectId: 'talk-hub-d1cf6',
    authDomain: 'talk-hub-d1cf6.firebaseapp.com',
    storageBucket: 'talk-hub-d1cf6.appspot.com',
    measurementId: 'G-XJL6LF0HET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8e9SYnbQjJIkN1bkeghd6kR35KyTqkvE',
    appId: '1:884044940776:android:d3aacacb42d9fce99a105d',
    messagingSenderId: '884044940776',
    projectId: 'talk-hub-d1cf6',
    storageBucket: 'talk-hub-d1cf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ4MGwbOEtDQyBPkByYIbbjidPPjSUmGo',
    appId: '1:884044940776:ios:f0c4be6de4ef35499a105d',
    messagingSenderId: '884044940776',
    projectId: 'talk-hub-d1cf6',
    storageBucket: 'talk-hub-d1cf6.appspot.com',
    androidClientId: '884044940776-fmkfnhjgmk0vbifr0aqok9etdn8cl9rs.apps.googleusercontent.com',
    iosClientId: '884044940776-722ddrusnqjmpju90vf0b21qnb83n50m.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ4MGwbOEtDQyBPkByYIbbjidPPjSUmGo',
    appId: '1:884044940776:ios:50c92f8f9336694b9a105d',
    messagingSenderId: '884044940776',
    projectId: 'talk-hub-d1cf6',
    storageBucket: 'talk-hub-d1cf6.appspot.com',
    androidClientId: '884044940776-fmkfnhjgmk0vbifr0aqok9etdn8cl9rs.apps.googleusercontent.com',
    iosClientId: '884044940776-ek2blbgsu4pkn83k6lcakg8kmnmgkd45.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkHub.RunnerTests',
  );
}
